const TOOL_LABELS: Record<string, string> = {
  fetch_url: 'Fetching website',
  lighthouse_audit: 'Running Lighthouse audit',
  ssl_check: 'Checking SSL certificate',
  seo_inventory: 'Checking SEO inventory',
  check_links: 'Checking links',
  playwright_audit: 'Running Playwright UX audit',
  detect_tech_stack: 'Detecting tech stack',
  dns_check: 'Checking DNS',
  search_stock_photos: 'Searching stock photos',
  resolve_contact: 'Looking up client',
  list_contacts: 'Listing clients',
  create_contact: 'Creating client',
  update_contact: 'Updating client',
  delete_contact: 'Deleting client',
  list_work: 'Listing projects',
  read_work: 'Reading project',
  create_work: 'Creating project',
  update_work: 'Updating project',
  delete_work: 'Deleting project',
  link_to_work: 'Linking to project',
  toggle_work_item: 'Updating checklist',
  get_work_invoice_suggestions: 'Preparing invoice suggestions',
  list_knowledge: 'Searching knowledge base',
  read_knowledge: 'Reading knowledge base',
  search_knowledge: 'Searching knowledge base',
  write_knowledge: 'Saving to knowledge base',
  list_documents: 'Listing document templates',
  read_document: 'Reading document template',
  preview_document: 'Rendering document preview',
  read_email_inbox: 'Reading email',
  list_email_inbox: 'Searching inbox',
  mark_email_junk: 'Marking email as junk',
  mark_email_receipt: 'Filing receipt',
  mark_email_routed: 'Routing email',
  delete_email: 'Deleting email',
  create_email_filter_rule: 'Creating email filter',
  send_email: 'Sending email',
  list_todos: 'Listing to-dos',
  create_todo: 'Creating to-do',
  update_todo: 'Updating to-do',
  mark_todo_done: 'Completing to-do',
  delete_todo: 'Deleting to-do',
  run_dev_task: 'Running dev task',
  list_railway_domains: 'Checking Railway domains',
  add_railway_domain: 'Adding Railway custom domain',
  list_railway_projects: 'Listing Railway projects',
  list_railway_services: 'Listing Railway services',
  list_railway_variables: 'Reading Railway variables',
  set_railway_variables: 'Setting Railway variables',
  delete_railway_variable: 'Deleting Railway variable',
  get_railway_service_config: 'Reading Railway service config',
  get_railway_status: 'Checking Railway status',
  list_railway_deployments: 'Listing Railway deployments',
  get_railway_logs: 'Fetching Railway logs',
  redeploy_railway_service: 'Redeploying Railway service',
  update_railway_service: 'Updating Railway service',
  create_railway_project: 'Creating Railway project',
  railway_whoami: 'Checking Railway account',
  list_railway_workspaces: 'Listing Railway workspaces',
  search_railway_docs: 'Searching Railway docs',
  sync_resend_dns: 'Syncing email DNS',
  cloudflare_dns: 'Managing Cloudflare DNS & SSL',
  namecom_dns: 'Managing Name.com DNS',
  namecom_ping: 'Checking Name.com credentials',
  namecom_list_domains: 'Listing Name.com domains',
  namecom_list_records: 'Listing Name.com DNS records',
  namecom_create_record: 'Creating Name.com DNS record',
  namecom_delete_record: 'Deleting Name.com DNS record',
  namecom_update_record: 'Updating Name.com DNS record',
  get_git_status: 'Checking git status',
  get_recent_commits: 'Reading recent commits',
  check_deployment_status: 'Checking deployment',
  list_open_branches: 'Listing branches',
  run_terminal_command: 'Running command',
  read_file: 'Reading file',
  grep_code: 'Searching code',
  write_file: 'Writing file',
  list_files: 'Listing files',
  exec_command: 'Running command',
  create_github_repo: 'Creating repository',
  create_github_branch: 'Creating branch',
  write_github_file: 'Writing file',
  read_github_file: 'Reading file',
  undo_website_change: 'Undoing last change',
  create_pull_request: 'Creating pull request',
  list_kinsta_sites: 'Listing Kinsta sites',
  create_kinsta_site: 'Creating Kinsta site',
  delete_kinsta_site: 'Deleting Kinsta site',
  backup_kinsta_site: 'Backing up site',
  clear_kinsta_cache: 'Clearing cache',
  get_kinsta_operation: 'Checking Kinsta operation',
  list_bookings: 'Listing bookings',
  get_booking: 'Reading booking',
  get_booking_link: 'Getting booking link',
  create_booking: 'Creating booking',
  sync_vapi_assistant: 'Syncing Vapi assistant',
  sync_uptimerobot: 'Syncing UptimeRobot monitors',
  get_demo_setup_status: 'Checking demo setup',
  run_demo_seed: 'Seeding demo data',
  set_client_portal: 'Configuring client portal',
  get_client_portal: 'Reading client portal',
  get_client_submit_link: 'Getting submit link',
  send_client_portal: 'Sending client portal',
  get_site_monitoring: 'Reading website monitoring',
  set_site_monitoring: 'Updating website monitoring',
  recheck_site_monitoring: 'Rechecking website monitoring',
  gsc_list_sites: 'Listing Search Console sites',
  gsc_search_analytics: 'Querying Search Console',
  gsc_inspect_url: 'Inspecting URL in Search Console',
  gsc_list_sitemaps: 'Listing sitemaps',
  gsc_submit_sitemap: 'Submitting sitemap',
  gsc_add_site: 'Adding Search Console property',
  plausible_stats: 'Fetching Plausible stats',
  ga4_list_properties: 'Listing GA4 properties',
  ga4_stats: 'Fetching GA4 stats',
  indexnow_submit_urls: 'Submitting IndexNow URLs',
  bing_webmaster_status: 'Checking Bing Webmaster',
};

function titleCaseWords(value: string): string {
  return value
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

export function labelForAgentTool(name: string): string {
  const trimmed = name.trim();
  if (!trimmed) return 'Working';
  return TOOL_LABELS[trimmed] ?? titleCaseWords(trimmed);
}
