/**
 * Daily property lead scan — radius geofence, trade filter, CRM intake.
 */
import { runRadiusScan, normalizeTradeSlugs, type ScanCandidate, type ScanCenterLocation } from '@reave/plugin-real-estate-data';
import { getCompanyConfig } from './companyConfig';
import { getDeploymentOwnerTimezone } from './deploymentOwner';
import { recordContactFormEngagement } from './engagementNotifications';
import { hasFeature } from './features';
import {
  getLeadScannerConfig,
  isLeadSeen,
  markLeadScannerRun,
  markLeadSeen,
  normalizeAddressKey,
  type LeadScannerConfig,
} from './leadScannerStore';
import { createLogger } from './logger';
import { ensureWorkContact, slugFromTitle, storeWriteWork } from './workStore';

const log = createLogger('lead-scanner');

export type LeadScannerRunResult = {
  ok: boolean;
  skipped?: string;
  candidatesFound?: number;
  newLeads?: number;
  skippedLeads?: number;
  errors?: string[];
  runId?: string;
};

export async function resolveScanCenter(
  config: LeadScannerConfig,
): Promise<{ lat: number; lng: number } | null> {
  if (config.centerLat != null && config.centerLng != null) {
    return { lat: config.centerLat, lng: config.centerLng };
  }
  if (config.useCompanyOffice) {
    const company = await getCompanyConfig();
    if (company.geo?.lat != null && company.geo?.lng != null) {
      return { lat: company.geo.lat, lng: company.geo.lng };
    }
  }
  return null;
}

export async function resolveScanLocation(
  center: { lat: number; lng: number },
): Promise<ScanCenterLocation> {
  const company = await getCompanyConfig();
  const { parseUsAddressLocation, reverseGeocode } = await import('./mapbox');
  const parsed = parseUsAddressLocation(company.address);
  if (parsed) return parsed;

  const reversed = await reverseGeocode(center.lat, center.lng);
  if (reversed) return reversed;

  return { city: 'Local Area', state: '', zip: '' };
}

function isScanWindow(
  config: LeadScannerConfig,
  timezone: string,
  now = new Date(),
  ignoreWindow = false,
): boolean {
  if (ignoreWindow) return true;
  try {
    const fmt = new Intl.DateTimeFormat('en-US', {
      timeZone: timezone,
      hour: 'numeric',
      hour12: false,
    });
    const hour = Number(fmt.format(now));
    return hour === config.scanHourLocal;
  } catch {
    return true;
  }
}

function leadProjectBody(candidate: ScanCandidate): string {
  const lines = [
    `# Property lead — ${candidate.fullAddress}`,
    '',
    `- **Score:** ${candidate.leadScore}/100`,
    `- **Distance:** ${candidate.distanceMiles} mi`,
    `- **Year built:** ${candidate.yearBuilt ?? 'unknown'}`,
    `- **Owner:** ${candidate.ownerName ?? 'unknown'}`,
    `- **Trades:** ${candidate.matchedTrades.join(', ')}`,
    '',
    '## Reasons',
    ...candidate.leadReasons.map((r) => `- ${r}`),
    '',
    '_Auto-generated by REΛVE Lead Scanner. Informational — verify before outreach._',
  ];
  return lines.join('\n');
}

async function intakeLead(candidate: ScanCandidate): Promise<{ ok: boolean; contactUid?: string; jobSlug?: string; error?: string }> {
  const owner = (candidate.ownerName ?? '').trim();
  const contactName = owner || `Property owner — ${candidate.street ?? candidate.fullAddress}`;

  const contact = await ensureWorkContact({
    contact_name: contactName,
  });

  if (!contact.ok) {
    return { ok: false, error: contact.error ?? 'Could not create or resolve contact' };
  }

  const tradeLabel = candidate.matchedTrades[0]?.replace(/_/g, ' ') ?? 'property';
  const title = `${tradeLabel} lead — ${candidate.street ?? candidate.fullAddress}`;
  const slug = slugFromTitle(title);

  const write = await storeWriteWork(slug, {
    title,
    contact_uid: contact.uid,
    contact_name: contactName,
    status: 'inquiry',
    source: 'lead_scanner',
    tags: ['lead-scanner', 'real-estate', ...candidate.matchedTrades],
    body: leadProjectBody(candidate),
  });

  if (!write.ok) {
    return { ok: false, error: write.error ?? 'Failed to create project' };
  }

  await recordContactFormEngagement({
    contactUid: contact.uid,
    contactName,
    jobSlug: slug,
    jobTitle: title,
    messagePreview: candidate.leadReasons.slice(0, 3).join(' · '),
  }).catch((e) => log.warn('engagement record failed', e));

  return { ok: true, contactUid: contact.uid, jobSlug: slug };
}

export function isLeadScannerEnabled(): boolean {
  return hasFeature('real_estate_data');
}

export async function runLeadScanner(options?: {
  source?: 'cron' | 'manual' | 'admin';
  ignoreWindow?: boolean;
  force?: boolean;
}): Promise<LeadScannerRunResult> {
  if (!isLeadScannerEnabled()) {
    return { ok: false, skipped: 'real_estate_data feature not enabled' };
  }

  const config = await getLeadScannerConfig();
  if (!config.enabled && !options?.force) {
    return { ok: false, skipped: 'Lead scanner disabled in admin settings' };
  }

  const timezone = await getDeploymentOwnerTimezone();
  if (!isScanWindow(config, timezone, new Date(), options?.ignoreWindow || options?.force)) {
    return { ok: false, skipped: `Outside scan window (hour ${config.scanHourLocal} ${timezone})` };
  }

  const center = await resolveScanCenter(config);
  if (!center) {
    return { ok: false, skipped: 'Set scan center on map or enable company office location' };
  }

  const centerLocation = await resolveScanLocation(center);
  const trades = normalizeTradeSlugs(config.trades);
  const scan = runRadiusScan({
    centerLat: center.lat,
    centerLng: center.lng,
    radiusMiles: config.radiusMiles,
    trades,
    maxResults: 50,
    centerLocation,
  });

  let newLeads = 0;
  let skipped = 0;
  const errors: string[] = [];

  for (const candidate of scan.candidates) {
    const addressKey = normalizeAddressKey(candidate.fullAddress);
    if (await isLeadSeen(candidate.id)) {
      skipped++;
      continue;
    }

    const intake = await intakeLead(candidate);
    if (!intake.ok) {
      errors.push(`${candidate.fullAddress}: ${intake.error ?? 'intake failed'}`);
      skipped++;
      continue;
    }

    await markLeadSeen({
      propertyId: candidate.id,
      addressKey,
      contactUid: intake.contactUid,
      jobSlug: intake.jobSlug,
    });
    newLeads++;
  }

  const runId = await markLeadScannerRun({
    source: options?.source ?? 'cron',
    candidatesFound: scan.candidatesFound,
    newLeads,
    skipped,
    errors,
  });

  log.info('scan complete', {
    candidates: scan.candidatesFound,
    newLeads,
    skipped,
    errors: errors.length,
  });

  return {
    ok: true,
    candidatesFound: scan.candidatesFound,
    newLeads,
    skippedLeads: skipped,
    errors,
    runId,
  };
}
