/**
 * North Shore debtor-bankruptcy fixtures — matters, inbox, and todos.
 */
import { DEMO_SEED_MARKER, type DemoChatDef, type DemoContactDef, type DemoEmailDef, type DemoJobDef, type DemoTodoDef } from '../demo-data.ts';

export const LAW_COMPANY = {
  name: 'Sample bankruptcy practice',
  tagline: 'Debtor representation — District of Massachusetts',
  supportEmail: 'intake@practice.demo',
  brandPrimary: '#1e3a5f',
  brandSecondary: '#b45309',
};

export const LAW_CONTACTS: DemoContactDef[] = [
  {
    key: 'sarah',
    name: 'Sarah Chen',
    email: 'sarah.chen@demo.reave.app',
    phone: '+19785550101',
    company: 'Chen Household',
    notes: `${DEMO_SEED_MARKER} Chapter 7 — credit cards + medical, Beverly`,
    address: '14 Hale St, Beverly, MA 01915',
    lat: 42.5584,
    lng: -70.8801,
    portal: {
      headline: 'Chapter 7',
      body: 'Petition is in draft. Upload the last 60 days of pay stubs and your credit-counseling certificate.',
      tagline: 'A fresh start, step by step.',
    },
  },
  {
    key: 'mike',
    name: 'Mike Rodriguez',
    email: 'mike@riverworks.demo',
    phone: '+19785550102',
    company: 'Rodriguez Household',
    notes: `${DEMO_SEED_MARKER} Chapter 13 — save the Peabody house`,
    address: '88 Washington St, Peabody, MA 01960',
    lat: 42.5279,
    lng: -70.9287,
  },
  {
    key: 'james',
    name: 'James Park',
    email: 'jpark@harborauto.demo',
    phone: '+19785550104',
    company: 'Harbor Auto Repair',
    notes: `${DEMO_SEED_MARKER} Stay violation — post-petition collection`,
    address: '210 Cabot St, Beverly, MA 01915',
    lat: 42.5476,
    lng: -70.8789,
  },
  {
    key: 'lisa',
    name: 'Lisa Nguyen',
    email: 'lisa@nguyen.demo',
    company: 'Nguyen Household',
    notes: `${DEMO_SEED_MARKER} 341 next week — Chapter 7`,
    address: '5 Flint St, Salem, MA 01970',
    lat: 42.5219,
    lng: -70.8955,
  },
  {
    key: 'david',
    name: 'David Walsh',
    email: 'dwalsh@walsh.demo',
    phone: '+19785550106',
    company: 'Walsh Household',
    notes: `${DEMO_SEED_MARKER} Reaffirmation — 2019 Honda CR-V`,
    address: '31 Ocean Ave, Marblehead, MA 01945',
    lat: 42.4982,
    lng: -70.8584,
  },
  {
    key: 'rachel',
    name: 'Rachel Brooks',
    email: 'rachel@brooksdental.demo',
    company: 'Brooks Dental',
    notes: `${DEMO_SEED_MARKER} Small-business Chapter 7 consult`,
    address: '100 Cummings Center, Beverly, MA 01915',
    lat: 42.5622,
    lng: -70.887,
  },
  {
    key: 'olivia',
    name: 'Olivia Grant',
    email: 'olivia@grantco.demo',
    phone: '+19785550115',
    company: 'Grant Household',
    notes: `${DEMO_SEED_MARKER} New intake — wage garnishment + cards`,
    address: '22 Lafayette St, Salem, MA 01970',
    lat: 42.5195,
    lng: -70.8967,
  },
  {
    key: 'counsel',
    name: 'Andrew Hale',
    email: 'ahale@halebarrett.demo',
    company: 'Hale & Barrett',
    notes: `${DEMO_SEED_MARKER} Creditor counsel — Capital One`,
    address: '60 State St, Boston, MA 02109',
    lat: 42.3586,
    lng: -71.0562,
  },
];

export const LAW_JOBS: DemoJobDef[] = [
  {
    slug: 'demo-sarah-chapter7',
    title: 'Chen — Chapter 7',
    contactKey: 'sarah',
    status: 'active',
    priority: 'high',
    dueDate: '2026-09-04',
    value: 1850,
    tags: ['chapter-7', 'consumer'],
    body: 'Beverly. Eastern Division (Boston), Judge Bostwick once filed. Waiting on pay stubs and counseling certificate. Means-test looks like a 7.',
  },
  {
    slug: 'demo-mike-chapter13',
    title: 'Rodriguez — Chapter 13',
    contactKey: 'mike',
    status: 'active',
    priority: 'high',
    dueDate: '2026-08-28',
    value: 3200,
    tags: ['chapter-13', 'mortgage'],
    body: 'Peabody house in arrears. Plan draft to Trustee Bankowski. Confirmation target after 341.',
  },
  {
    slug: 'demo-james-stay-violation',
    title: 'Harbor Auto — stay violation',
    contactKey: 'james',
    status: 'active',
    priority: 'urgent',
    dueDate: '2026-08-22',
    value: 2400,
    tags: ['stay', 'chapter-7'],
    body: 'Filed last Tuesday. Ally supply house called the shop yesterday demanding the parts invoice. Draft stay letter and, if needed, a motion.',
  },
  {
    slug: 'demo-lisa-341',
    title: 'Nguyen — 341 prep',
    contactKey: 'lisa',
    status: 'active',
    priority: 'urgent',
    dueDate: '2026-08-26',
    value: 1850,
    tags: ['chapter-7', '341'],
    body: '341 on Zoom with trustee Cruickshank. Need tax returns uploaded and a 2-page outline for Lisa.',
  },
  {
    slug: 'demo-david-reaffirm',
    title: 'Walsh — auto reaffirmation',
    contactKey: 'david',
    status: 'active',
    priority: 'normal',
    dueDate: '2026-09-02',
    value: 750,
    tags: ['reaffirmation', 'chapter-7'],
    body: 'Honda CR-V. Lender sent the reaffirmation agreement. Review payment and ride-through options before the client signs.',
  },
  {
    slug: 'demo-olivia-intake',
    title: 'Grant — new intake',
    contactKey: 'olivia',
    status: 'inquiry',
    priority: 'high',
    tags: ['intake', 'garnishment'],
    body: 'Wage garnishment out of Salem District plus ~$28k cards. Conflict check clear. Retainer not signed. Counseling not started.',
  },
];

export const LAW_EMAILS: DemoEmailDef[] = [
  {
    id: 'demo-email-sarah-stubs',
    from: 'Sarah Chen <sarah.chen@demo.reave.app>',
    subject: 'Pay stubs — last two months',
    bodySnippet: 'Attached are June and July from the hospital. Counseling class is booked for Thursday night.',
    bodyText:
      'Hi —\n\nAttached are June and July pay stubs from Beverly Hospital. I booked the credit-counseling class for Thursday night and will send the certificate as soon as I have it.\n\nSarah',
    category: 'client',
    status: 'MATCHED',
    action: 'classified',
    contactKey: 'sarah',
    jobSlug: 'demo-sarah-chapter7',
    summary: 'Chen sent pay stubs; counseling booked Thursday.',
    daysAgo: 0,
  },
  {
    id: 'demo-email-stay',
    from: 'James Park <jpark@harborauto.demo>',
    subject: 'Ally called the shop again',
    bodySnippet: 'They want the $4,200 parts invoice. I told them we filed. Can you send something today?',
    bodyText:
      'Ally’s collector called the front desk again this morning about the $4,200 parts bill. I said we filed Tuesday. Can you send them something today so they stop calling the bays?\n\nJames / Harbor Auto',
    category: 'project',
    status: 'MATCHED',
    action: 'classified',
    contactKey: 'james',
    jobSlug: 'demo-james-stay-violation',
    summary: 'Post-petition collection call — client wants a stay letter today.',
    daysAgo: 0,
  },
  {
    id: 'demo-email-trustee',
    from: 'Gary W. Cruickshank <gwc@cruickshank-law.com>',
    subject: 'Nguyen 26-10412 — tax returns',
    bodySnippet: 'Please upload 2024 federal and MA returns before the 341. Zoom credentials are on the 309.',
    bodyText:
      'Counsel — please upload the 2024 federal and Massachusetts returns for Lisa Nguyen (26-10412) before the § 341. Zoom credentials are on the Notice of Bankruptcy Case.\n\nGary W. Cruickshank, Chapter 7 Trustee',
    category: 'project',
    status: 'MATCHED',
    action: 'classified',
    contactKey: 'lisa',
    jobSlug: 'demo-lisa-341',
    summary: 'Trustee Cruickshank wants 2024 returns before the 341.',
    daysAgo: 1,
  },
  {
    id: 'demo-email-court',
    from: 'U.S. Bankruptcy Court <ecf@mab.uscourts.gov>',
    subject: '341 meeting notice — Nguyen, Lisa',
    bodySnippet: 'Meeting of creditors set. Appear via Zoom using the trustee credentials on the notice.',
    bodyText:
      'A meeting of creditors under 11 U.S.C. § 341 is set in Nguyen, Lisa.\n\nDivision: Eastern (Boston). Judge: Janet E. Bostwick. Appear via Zoom using the trustee credentials on Official Form 309.\n\nUnited States Bankruptcy Court, District of Massachusetts',
    category: 'alert',
    status: 'MATCHED',
    action: 'classified',
    contactKey: 'lisa',
    jobSlug: 'demo-lisa-341',
    summary: 'Court 341 notice — Eastern Division, Judge Bostwick, Zoom.',
    daysAgo: 2,
  },
  {
    id: 'demo-email-new-intake',
    from: 'Olivia Grant <olivia@grantco.demo>',
    subject: 'They started taking money from my paycheck',
    bodySnippet: 'Salem District garnishment. Cards too. Can we talk this week before the next payday?',
    bodyText:
      'Hello — a collector got a garnishment out of Salem District Court and my employer started withholding this week. I also have about $28,000 on cards.\n\nCan we talk before Friday payday?\n\nOlivia Grant',
    category: 'review',
    status: 'UNMATCHED',
    action: 'classified',
    summary: 'New intake — Salem District wage garnishment plus credit cards.',
    daysAgo: 0,
  },
  {
    id: 'demo-email-creditor',
    from: 'Andrew Hale <ahale@halebarrett.demo>',
    subject: 'Capital One — Rodriguez 13',
    bodySnippet: 'We will file a proof of claim on the Visa. Please confirm the plan treatment for unsecureds.',
    bodyText:
      'Counsel — Capital One will file a proof of claim on the Rodriguez Chapter 13 Visa. Please confirm the plan treatment for general unsecureds.\n\nAndrew Hale\nHale & Barrett',
    category: 'project',
    status: 'MATCHED',
    action: 'classified',
    contactKey: 'counsel',
    jobSlug: 'demo-mike-chapter13',
    summary: 'Creditor counsel will file a POC on the Rodriguez 13.',
    daysAgo: 1,
  },
];

export const LAW_CHATS: DemoChatDef[] = [
  {
    title: '[Demo] Stay letter — Harbor Auto',
    messages: [
      {
        role: 'user',
        content: 'Ally called James at the shop after we filed. Draft the stay letter.',
      },
      {
        role: 'assistant',
        content:
          '**Harbor Auto — stay violation** is urgent. Case filed Tuesday; Ally called the bays this morning on a $4,200 parts invoice.\n\nI’ll draft a short stay letter citing the petition date and 11 U.S.C. § 362, and put a follow-up todo if they call again. Want it on your letterhead to the collector and to James?',
      },
    ],
  },
  {
    title: '[Demo] Where is Lisa’s 341?',
    messages: [
      {
        role: 'user',
        content: 'Where does Lisa go for the 341? Is Bostwick in the room?',
      },
      {
        role: 'assistant',
        content:
          'No — the 341 is not in front of Judge Bostwick. Eastern Division 341s are **Zoom with the panel trustee**. Lisa is with **Gary Cruickshank**. Credentials are on her Form 309.\n\nIf the UST ever forces in-person, it’s McCormack **Suite 1000**, 5 Post Office Square — not the clerk at 1150. I still need her 2024 returns uploaded before the meeting.',
      },
    ],
  },
  {
    title: '[Demo] Open intake',
    messages: [
      {
        role: 'user',
        content: 'Any new matters waiting on a retainer?',
      },
      {
        role: 'assistant',
        content:
          'One: **Olivia Grant** — Salem District wage garnishment plus about $28k in cards. Conflict check is clear. Retainer not signed; counseling not started.\n\nChen 7 is waiting on the counseling certificate. Rodriguez 13 is in plan draft for Bankowski.',
      },
    ],
  },
];

export const LAW_TODOS: DemoTodoDef[] = [
  {
    title: 'Stay letter to Ally — Harbor Auto',
    section: 'Today',
    priority: 'urgent',
    jobSlug: 'demo-james-stay-violation',
    daysUntilDue: 0,
  },
  {
    title: 'Upload Nguyen 2024 returns for Cruickshank',
    section: 'Today',
    priority: 'urgent',
    jobSlug: 'demo-lisa-341',
    daysUntilDue: 0,
  },
  {
    title: '341 outline — Lisa Nguyen',
    section: 'Today',
    priority: 'high',
    jobSlug: 'demo-lisa-341',
    daysUntilDue: 0,
  },
  {
    title: 'Chase Chen counseling certificate',
    section: 'This week',
    priority: 'high',
    jobSlug: 'demo-sarah-chapter7',
    daysUntilDue: 2,
  },
  {
    title: 'Rodriguez 13 plan to Bankowski',
    section: 'This week',
    priority: 'high',
    jobSlug: 'demo-mike-chapter13',
    daysUntilDue: 3,
  },
  {
    title: 'Review Walsh CR-V reaffirmation',
    section: 'This week',
    priority: 'normal',
    jobSlug: 'demo-david-reaffirm',
    daysUntilDue: 4,
  },
  {
    title: 'Grant retainer + Salem garnishment docket',
    section: 'This week',
    priority: 'high',
    jobSlug: 'demo-olivia-intake',
    daysUntilDue: 2,
  },
];
